### ISSUE TITLE
PostPage.js form button관련 이슈

### ISSUE THREAD

**Issue by FoocoJun** [FoocoJun/miniproject-FE#19]
## `PostPage.js` 코드 일부입니다.

```jsx
return (
    <ComponentBox>
        <Title> 밤의 이야기 </Title>
            <PostBox>
                <FortuneTextBox>
                    {/* 운세글 get */}
                    <FortuneText> 아침에 옆사람 뒷통수를 <br /> 때리면 즐거울거야. </FortuneText>
                </FortuneTextBox>
                <InputStyle rows="3" cols="20" wrap="hard"  placeholder="내용을 입력하세요."/>
            </PostBox>
        <MediumButton onClick={() => navigate("/fortune/signin")}> 작성하기 </MediumButton>
    </ComponentBox>
  )
```
## 현재 구조는 아래와 같습니다.
```jsx
<PostBox>             {/* form 여는 태그*/}
    <FortuneTextBox/>        {/* 운세 텍스트*/}
    <InputStyle/>            {/* 일기 input*/}
</PostBox>            {/* form 닫는 태그*/}
<MediumButton/>       {/* 버튼*/}
```

### 여기서 문제가 발생합니다.
**input은 form 내부에 있으나 button이 form 외부에 있습니다.**
- 그렇기 때문에 **Button에 의한 `onSubmit` 작동이 불가**능합니다.
- 또한 **required 유효성검사를 실행할 수 없습니다.**

하지만 스타일드 컴포넌트가 많이 적용되어 있어서 순서를 쉽게 바꾸기도 어렵습니다.
급하게 수정하려다가 지금의 무게중심 레이아웃이 너무 좋아서 일단 이슈로 등록합니다.

### 예상 가능한 두가지 해결방법이 있습니다.
1. **버튼의 위치를 PostBox 내부에 넣고 스타일을 재조정** 한다.
2. 기본 유효성검사를 포기하고 **onClick에 유효성 검사를 포함하여 submit시 제공할 계획이었던 함수를 포함하여 작성**한다.
    - 이렇게 되면 로그인 로그아웃 페이지에서 사용하는 기본 HTML 유효성 검사와는 다르게 나타날 예정.

**Comment by INSOCCI** [comment]
오 감사합니다 ! 얼른 확인하고 해결 후 다시 알려드리겠습니다 !!
